##### RSS-BRIDGE #####
# Fully Qualified Domain Name for the rss-bridge instance
rss_bridge_fqdn: "rss-bridge.CHANGEME.org"
# yes/no: enable username/password authentication for all requests going to rss-bridge
rss_bridge_auth_enabled: yes
# rss_bridge login and password, when authentication is enabled
rss_bridge_auth_username: "CHANGEME"
rss_bridge_auth_password: "CHANGEME"
