- name: include variable checks tasks
  include: checks.yml
  tags:
    - monitoring
    - netdata
    - checks

- name: include netdata configuration tasks
  include: netdata.yml
  become: yes
  tags:
    - monitoring
    - netdata

- name: include ansible facts configuration tasks
  include: fact.yml
  become: yes
  tags:
    - monitoring
    - netdata

- name: include netdata-netdata-module-needrestart configuration tasks
  include: netdata-module-needrestart.yml
  become: yes
  tags:
    - monitoring
    - netdata
    - netdata-modules
    - netdata-needrestart
  when: setup_needrestart | bool

- name: include netdata-module-logcount configuration tasks
  include: netdata-module-logcount.yml
  become: yes
  tags:
    - monitoring
    - netdata
    - netdata-modules
    - netdata-logcount
  when: setup_netdata_logcount | bool

- name: include netdata-module-debsecan configuration tasks
  include: netdata-module-debsecan.yml
  become: yes
  tags:
    - monitoring
    - netdata
    - netdata-modules
    - netdata-debsecan
  when: setup_netdata_debsecan | bool

- name: include firewalld configuration tasks
  include: firewalld.yml
  become: yes
  tags:
    - monitoring
    - netdata
    - firewall
  when:
    - ansible_local.firewalld.ansible_managed is defined
    - ansible_local.firewalld.ansible_managed | bool

- name: apply configuration (flush handlers)
  meta: flush_handlers
  tags:
    - monitoring
    - netdata
    - firewall

##### UTILITIES ####
# These tasks are tagged 'never' and will never run unless one of their tags is explicitly passed on the command line
- name: include netdata notification testing tasks
  include: utils-netdata-test-notifications.yml
  tags:
    - never
    - utils-netdata-test-notifications

- name: include automatic reboot/restart tasks
  become: yes
  include: utils-autorestart.yml
  tags:
    - never
    - utils-autorestart
