---
- name: sysctl
  become: 'yes'
  template:
    src: etc/sysctl.conf.j2
    dest: /etc/sysctl.conf
    backup: 'yes'
    mode: 0600
    owner: root
    group: root
  notify:
    - restart sysctl
  tags:
    - sysctl
...
