---

- name: limits.conf
  become: 'yes'
  template:
    src: etc/security/limits.conf.j2
    dest: /etc/security/limits.conf
    backup: 'yes'
    mode: 0644
    owner: root
    group: root
  tags:
    - limits.conf

- name: coredump.conf
  become: 'yes'
  template:
    src: etc/systemd/coredump.conf.j2
    dest: /etc/systemd/coredump.conf
    backup: 'yes'
    mode: 0644
    owner: root
    group: root
  tags:
    - coredump.conf
    - systemd
...
