---
- name: adduser.conf
  become: 'yes'
  template:
    src: etc/adduser.conf.j2
    dest: /etc/adduser.conf
    backup: 'yes'
    mode: 0644
    owner: root
    group: root
  tags:
    - adduser.conf

- name: useradd
  become: 'yes'
  template:
    src: etc/default/useradd.j2
    dest: /etc/default/useradd
    backup: 'yes'
    mode: 0644
    owner: root
    group: root
  tags:
    - useradd
...
