---
- name: remove users
  become: 'yes'
  user:
    name: "{{ item }}"
    state: absent
    remove: 'yes'
  with_items:
    - games
    - gnats
    - irc
    - list
    - news
    - sync
    - uucp
  ignore_errors: true
  tags:
    - users
...
