---
- name: remove suid/sgid
  become: 'yes'
  file:
    path: "{{ item }}"
    mode: 'a-s'
    state: file
    follow: 'yes'
  ignore_errors: true
  with_items:
    - "{{ suid_sgid_blocklist }}"
  tags:
    - suid
...
