---
- name: systemd logind
  become: 'yes'
  template:
    src: etc/systemd/logind.conf.j2
    dest: /etc/systemd/logind.conf
    backup: 'yes'
    mode: 0644
    owner: root
    group: root
  notify:
    - reload systemd
  tags:
    - systemd
    - logind
...
