---
- name: disable apport
  become: 'yes'
  lineinfile:
    regexp: "^enabled="
    line: "enabled=0"
    dest: /etc/default/apport
    mode: 0644
    state: present
    create: 'no'
    backrefs: 'yes'
  ignore_errors: true
  notify:
    - mask apport
  when: ansible_os_family == "Debian"
  tags:
    - apport
...
