---
- name: sudo use_pty
  become: 'yes'
  lineinfile:
    line: "Defaults use_pty"
    dest: /etc/sudoers.d/011_use_pty
    mode: 0440
    state: present
    create: 'yes'
  tags:
    - sudo

- name: sudo configure logfile
  become: 'yes'
  lineinfile:
    line: 'Defaults logfile="/var/log/sudo.log"'
    dest: /etc/sudoers.d/012_logfile
    mode: 0440
    state: present
    create: 'yes'
  tags:
    - sudo

- name: sudo disable pwfeedback
  become: 'yes'
  lineinfile:
    line: "Defaults !pwfeedback"
    dest: /etc/sudoers.d/013_pwfeedback
    mode: 0440
    state: present
    create: 'yes'
  tags:
    - sudo

- name: sudo disable visiblepw
  become: 'yes'
  lineinfile:
    line: "Defaults !visiblepw"
    dest: /etc/sudoers.d/014_visiblepw
    mode: 0440
    state: present
    create: 'yes'
  tags:
    - sudo

- name: sudo passwd_timeout
  become: 'yes'
  lineinfile:
    line: "Defaults passwd_timeout=5"
    dest: /etc/sudoers.d/15_timeout
    mode: 0440
    state: present
    create: 'yes'
  tags:
    - sudo
...
