- name: check that mandatory variables are correctly defined
  assert:
    quiet: yes
    that:
      - ansible_user_allow_sudo_rsync_nopasswd == ansible_user_allow_sudo_rsync_nopasswd|bool
      - dns_nameservers|type_debug == "list"
      - linux_users|type_debug == "list"
      - os_security_kernel_enable_core_dump == os_security_kernel_enable_core_dump|bool
      - setup_apt == setup_apt|bool
      - apt_unattended_upgrades_origins_patterns|type_debug == "list"
      - setup_cli_utils == setup_cli_utils|bool
      - setup_dns == setup_dns|bool
      - setup_hosts == setup_hosts|bool
      - setup_firewall == setup_firewall|bool
      - firewalld|type_debug == "list"
      - setup_fail2ban == setup_fail2ban|bool
      - setup_haveged == setup_haveged|bool
      - setup_msmtp == setup_msmtp|bool
      - setup_ssh == setup_ssh|bool
      - ssh_permit_root_login in ['yes', 'no', 'without-password', 'prohibit-password', 'forced-commands-only']
      - ssh_kexalgorithms|type_debug == "list"
      - ssh_hmacs|type_debug == "list"
      - setup_datetime == setup_datetime|bool
      - setup_sysctl == setup_sysctl|bool
      - ssh_allow_tcp_forwarding in ['no', 'local', 'remote', 'all']
      - ssh_authorized_keys|type_debug == "list"
      - ssh_log_level in ['QUIET', 'FATAL', 'ERROR', 'INFO', 'VERBOSE', 'DEBUG', 'DEBUG1', 'DEBUG2', 'DEBUG3']
      - ssh_server_revoked_keys|type_debug == "list"
      - ssh_sftp_loglevel in ['QUIET', 'FATAL', 'ERROR', 'INFO', 'VERBOSE', 'DEBUG', 'DEBUG1', 'DEBUG2', 'DEBUG3']
      - sysctl_allow_forwarding == sysctl_allow_forwarding|bool
      - sysctl_answer_ping == sysctl_answer_ping|bool
      - sysctl_vm_swappiness|int
      - sysctl_vm_vfs_cache_pressure|int

- name: check that mandatory variables are correctly defined (msmtp)
  assert:
    quiet: yes
    that:
      - msmtp_host is not search("CHANGEME")
      - msmtp_port == msmtp_port|int
      - msmtp_auth_enabled == msmtp_auth_enabled|bool
      - msmtp_tls_enabled == msmtp_tls_enabled|bool
      - msmtp_admin_email is not search("CHANGEME")
      - msmtp_from is string
      - msmtp_starttls == msmtp_starttls|bool
  when: setup_msmtp|bool
  tags:
    - mail
    - msmtp

- name: check that mandatory variables are correctly defined (msmtp authentication)
  assert:
    quiet: yes
    that:
      - msmtp_username is not search("CHANGEME")
      - msmtp_password is not search("CHANGEME")
  when:
    - setup_msmtp|bool
    - msmtp_auth_enabled|bool
  tags:
    - mail
    - msmtp

- name: check that variables are correctly defined (hosts)
  assert:
    quiet: yes
    that:
      - item.ip_address|ansible.netcommon.ipaddr
      - (item.state is not defined) or (item.state in ['present', 'absent'])
  with_items: "{{ hosts }}"
  when: setup_hosts|bool
  tags: hosts

- name: check that variables are correctly defined (firewalld_zone_sources)
  assert:
    quiet: yes
    that:
      - item.zone is string
      - item.sources|type_debug == "list"
      - (item.state is not defined) or (item.state in ['enabled','disabled'])
      - (item.permanent is not defined) or (item.permanent == item.permanent|bool)
      - (item.immediate is not defined) or (item.immediate == item.permanent|bool)
  with_items: "{{ firewalld_zone_sources }}"
  when:
    - setup_firewall|bool
    - (item.delete is not defined) or (not item.delete)
  tags:
    - firewall
    - firewalld

- name: check that variables are correctly defined (firewalld_zone_services)
  assert:
    quiet: yes
    that:
      - item.zone is string
      - item.services|type_debug == "list"
      - (item.state is not defined) or (item.state in ['enabled','disabled'])
      - (item.permanent is not defined) or (item.permanent == item.permanent|bool)
      - (item.immediate is not defined) or (item.immediate == item.permanent|bool)
  with_items: "{{ firewalld_zone_services }}"
  when: setup_firewall|bool
  tags:
    - firewall
    - firewalld
