- include: checks.yml
  tags:
    - common
    - checks

- include: hostname.yml
  become: yes
  tags:
    - common
    - hostname

- include: hosts.yml
  become: yes
  tags:
    - common
    - hosts
  when: setup_hosts|bool

- include: dns.yml
  become: yes
  tags:
    - common
    - dns
  when: setup_dns|bool

- include: sysctl.yml
  become: yes
  tags:
    - common
    - sysctl
  when: setup_sysctl|bool

- include: apt.yml
  become: yes
  tags:
    - common
    - apt
  when: setup_apt|bool

- include: datetime.yml
  become: yes
  tags:
    - common
    - datetime
  when: setup_datetime|bool

- include: ssh.yml
  become: yes
  tags:
    - common
    - ssh
  when: setup_ssh|bool

- include: firewalld.yml
  become: yes
  tags:
    - common
    - firewall
    - firewalld
  when: setup_firewall|bool

- include: fail2ban.yml
  become: yes
  tags:
    - common
    - fail2ban
  when: setup_fail2ban|bool

- include: auditd.yml
  become: yes
  tags:
    - common
    - auditd

- include: users.yml
  become: yes
  tags:
    - common
    - users

- include: mail.yml
  become: yes
  tags:
    - common
    - mail
    - msmtp

- include: packages.yml
  become: yes
  tags:
    - common
    - packages

- include: fact.yml
  become: yes
  tags: common

- name: apply configuration (flush handlers)
  meta: flush_handlers
  tags: common

##### UTILITIES ####
# These tasks are tagged 'never' and will never run unless one of their tags is explicitly passed on the command line
- include: debian10to11.yml
  become: yes
  tags:
    - never
    - debian10to11
