##### APACHE WEB SERVER #####
# yes/no: listen on port 80 (unencrypted HTTP)
apache_listen_http: yes
# yes/no: ask search engines/bots that respect the X-Robots-Tag header not to crawl this webserver's sites
apache_allow_robots: no
# yes/no: start/stop the apache webserver, enable/disable it on boot
apache_enable_service: yes
# yes/no: enable mod_evasive for basic DoS protection (can interfere with legitimate traffic)
apache_enable_mod_evasive: no
# e-mail address to register a letsencrypt.org account
apache_letsencrypt_email: "CHANGEME"
# yes/no: aggregate apache access logs to syslog (if monitoring role is enabled and setup_rsyslog is true)
apache_access_log_to_syslog: no
# firewall zones for the apache service, if nodiscc.xsrv.common/firewalld role is deployed
# 'zone:' is one of firewalld zones, set 'state:' to 'disabled' to remove the rule (the default is state: enabled)
# apache access must be allowed from the 'public' zone to use Let's Encrypt certificates
apache_firewalld_zones:
  - zone: public
    state: enabled
  - zone: internal
    state: enabled

##### PHP-FPM INTERPRETER #####
# yes/no: enable/disable the default php-fpm pool (www)
# starting php-fpm without any pool defined will cause the service to fail
php_fpm_enable_default_pool: yes

# yes/no: add the ansible user account to the www-data group
# when this is enabled a link to the webserver root directory will be created in the ansible user's home directory
apache_ansible_user_in_www_data_group: no

